[functions]
    external_node_modules = ["express"]
    node_bundler = "esbuild"
    directory = "backend/api"

    [functions."netlify-cronjobs"]
        schedule = "*/1 * * * *"

[[redirects]]
    force = true
    from = "/api/*"
    status = 200
    to = "/.netlify/functions/api/netlify-api" # can also use ":splat" to refer to what "*" matched
