[build]
  # Builds all of front/back/shared, and installs shared to backend
  command = "yarn setup:local && yarn build && yarn build:back:netlify"

  # Directory that contains the deploy-ready web assets (doesn't affect functions in any way)
  publish = "frontend/dist"

  # This prevents pushes to GitHub from triggering builds, but still lets us trigger one via hooks
  # The other way of achieving the same is setting the production branch of the site to something
  # that doesn't exist (e.g. "NONE"), but that seems to disable scheduled functions.
  # See: https://answers.netlify.com/t/build-deploy-via-webhook-only/2516/13
  # See: https://docs.netlify.com/configure-builds/ignore-builds/
  ignore = "exit 0"

[functions]
  node_bundler = "esbuild"
  directory = "backend/entrypoints"

  # Run our cronjobs on a schedule. Note that scheduled functions only run on published deploys.
  # They don’t run on Deploy Previews or branch deploys.
  # See: https://docs.netlify.com/functions/scheduled-functions/
  [functions."netlify-cronjobs"]
    schedule = "*/3 * * * *" # once every 3 minutes

# This is more of a "rewrite" than a "redirect", and just makes our functions available under a more
# pleasant path (the default is pretty verbose)
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/netlify-api" # can also use ":splat" to refer to what "*" matched
  status = 200
  force = true

# This lets us do routing on the frontend, even when the initial request isn't just "/"
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  force = false
