version: '3'
services:
  nightbear_db_test:
    image: postgres:16
    container_name: nightbear-db-test
    restart: always
    environment:
      - POSTGRES_DB=nightbear_test
      - POSTGRES_USER=nightbear
      - POSTGRES_PASSWORD=nightbear
    ports:
      - '35432:5432'

  nightbear_db_local:
    image: postgres:16
    container_name: nightbear-db-local
    restart: always
    environment:
      - POSTGRES_DB=nightbear_local
      - POSTGRES_USER=nightbear
      - POSTGRES_PASSWORD=nightbear
    ports:
      - '25432:5432'
    volumes:
      - .:/app # this lets us exchange data easily with COPY
