[functions]
    external_node_modules = ["express"]
    node_bundler = "esbuild"
    directory = "backend/api"
[[redirects]]
    force = true
    from = "/*"
    status = 200
    to = "/backend/api/:splat"
