#!/usr/bin/env node

/**
 * Use this script to check the revision that is currently in a specific environment (e.g. LIVE, STAGING).
 *
 * @example $ s3-current staging
 */

/* eslint-disable */

var config = {
  env: process.argv[2],
  s3Region: process.env.AWS_DEFAULT_REGION || 'eu-west-1'
};

config.bucketName = 'nightbear.fi';
config.inputFile = config.env + '.html';
config.inputUrl = 'https://s3-' + config.s3Region + '.amazonaws.com/' + config.bucketName + '/' + config.inputFile;

var axios = require('axios'); // @see https://github.com/mzabriskie/axios

axios.get(config.inputUrl)
  .then(function(res) {
    var match = res.data.match(/data-app-rev="(.*?)"/);
    if (match) {
      console.log(match[1]);
    } else {
      console.error(config);
      console.error('Could not find "data-app-rev" from:\n\n' + res.data);
      process.exit(1);
    }
  })
  .catch(function(err) {
    console.error(config);
    console.error('Something went wrong:', err);
    process.exit(1);
  });
