#!/bin/bash

set -euo pipefail # exit on error; treat unset variables as errors; exit on errors in piped commands

if [ "$#" -ne 2 ]; then
  echo -e "Usage: <env> <file>" >&2
  exit 1
fi

DIR="$(dirname "$(readlink -f "${BASH_SOURCE[0]}")")" # figure out current script path
DATABASE_URL="$("$DIR/env" ${1:-})" # set correct DATABASE_URL for this env
DATABASE_URL="${DATABASE_URL/@localhost/@host.docker.internal}" # localhost won't be directly reachable → update if needed

docker run --rm -i postgres:16 pg_dump --no-owner "$DATABASE_URL" > "$2" # dump the selected DB to file
