#!/bin/bash

set -euo pipefail # exit on error; treat unset variables as errors; exit on errors in piped commands

DIR="$(dirname "$(readlink -f "${BASH_SOURCE[0]}")")" # figure out current script path
ENV="$("$DIR/env" $1)" # make sure we exit if the env isn't valid
eval "$ENV" # set correct DATABASE_URL for this env

DATABASE_URL="$(echo "$DATABASE_URL" | sed s/@localhost/@host.docker.internal/)" # localhost won't be directly reachable → update if needed
docker run --rm -it -v "$(pwd)":/app postgres:16 psql "$DATABASE_URL"
