#!/bin/bash

set -euo pipefail # exit on error; treat unset variables as errors; exit on errors in piped commands

# Prepare for running Terraform commands:
cd infra
source .envrc

# Start tunnel:
$(terraform output -json | jq -r .global_bastion.value.tunnel_command)
