import * as sensorEntries from 'backend/db/sensorEntries/db.queries';
import * as cronjobsJournal from 'backend/db/cronjobsJournal/db.queries';
import _ from 'lodash';
import { Client, Pool, types } from 'pg';

/**
 * All DB modules need to be listed here to become accessible via the DB wrapper.
 */
const dbModules = {
  sensorEntries,
  cronjobsJournal,
};

/**
 * @see https://pgtyped.dev/docs/typing
 */
types.setTypeParser(types.builtins.NUMERIC, value => parseFloat(value));

export type DbClient = ReturnType<typeof createDbClient>;

/**
 * Creates a Postgres wrapper for talking to the database.
 */
export function createDbClient(connectionString: string) {
  return wrapQueries(dbModules, new Pool({ connectionString }));
}

/**
 * Updates the DB modules generated by pgtyped to not require manually passing in a DB connection.
 */
function wrapQueries<
  T extends Record<string, Record<string, { run: (params: any, client: Client) => Promise<unknown> }>>,
>(db: T, pool: Pool) {
  return _.mapValues(db, methods =>
    _.mapValues(methods, (method: any) => (args: any) => performQuery(method, args, pool)),
  ) as unknown as {
    [K1 in keyof T]: {
      [K2 in keyof T[K1]]: (params: Parameters<T[K1][K2]['run']>[0]) => ReturnType<T[K1][K2]['run']>;
    };
  };
}

/**
 * Performs the actual query against the DB. Also converts rows from snake_case to camelCase.
 */
async function performQuery(
  query: { run: (args: unknown, client: Pool) => Promise<Record<string, unknown>[]> },
  args: unknown,
  pool: Pool,
) {
  const res = await query.run(args, pool);
  return res.map(row => _.mapKeys(row, (_val, key) => _.camelCase(key)));
}
