name: CI run

on:
  push:
    branches-ignore:
      - master # pushes to "master" are handled by the CD workflow

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '18.16.1'
      - run: npm install
      - run: npm run lint
      - run: npm test
