# https://help.github.com/en/actions/automating-your-workflow-with-github-actions/configuring-a-workflow
# https://itnext.io/automate-your-integration-tests-and-semantic-releases-with-github-actions-43875ad83092

name: Continuous Integration

on: [push]

jobs:
  qa:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '8.10'
      - run: npm install
      - run: npm run lint
      - run: npm test
