name: Deploy stage

on:
  push:
    branches:
      - master
      - test-deploy-stage # you can push to this branch to test the stage-deploy process, without having to iterate on master, potentially interfering with others' work

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '18.16.1'
      - run: npm install
      - run: npm run lint
      - run: npm test
      - run: npm run front:build
      - name: Deploy frontend
        uses: jakejarvis/s3-sync-action@v0.5.1
        with:
          args: --acl public-read --follow-symlinks --delete --cache-control no-store,must-revalidate
        env:
          AWS_S3_BUCKET: nightbear-stage-ui-content
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          SOURCE_DIR: build
      - name: Deploy server
        uses: appleboy/ssh-action@master
        with:
          host: hosting.nightbear.fi
          username: ${{ secrets.DEPLOY_SSH_USERNAME }}
          key: ${{ secrets.DEPLOY_SSH_PRIVATE_KEY }}
          script: |
            set -xeuo pipefail # print our commands back; exit on error; treat unset variables as errors; exit on errors in piped commands
            cd server-stage && git fetch && git checkout origin/master
            echo "$(echo ${{ github.ref }} | cut -d / -f 3) ($(git rev-parse --short HEAD) deployed $(date --iso-8601=seconds))" > .nightbear-deploy-version # github.ref will be e.g. "refs/heads/master"
            docker restart server-stage
