name: Deploy stage

on:
  push:
    branches:
      - master
      - test-deploy-stage # you can push to this branch to test the stage-deploy process, without having to iterate on master, potentially interfering with others' work

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '8.10'
      - run: npm install
      - run: npm run lint
      - run: npm test
      - run: npm run web-build
      - name: Deploy frontend
        uses: jakejarvis/s3-sync-action@v0.5.1
        with:
          args: --acl public-read --follow-symlinks --delete --cache-control no-store,must-revalidate
        env:
          AWS_S3_BUCKET: aws-static-site---stage-nightbear-fi
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          SOURCE_DIR: build
      - name: Deploy server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.DEPLOY_SSH_HOST }}
          username: ${{ secrets.DEPLOY_SSH_USERNAME }}
          key: ${{ secrets.DEPLOY_SSH_PRIVATE_KEY }}
          script: cd server-stage && git pull && docker-compose restart server_stage
