name: Deploy stage

on:
  push:
    branches:
      - master
      - test-deploy-stage # you can push to this branch to test the stage-deploy process, without having to iterate on master, potentially interfering with others' work

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Print GITHUB_REF for deploy debugging
        run: echo GITHUB_REF=$GITHUB_REF
