name: Deploy stage

on:
  push:
    branches:
      - next # we deploy the main branch automatically to the stage env
      - test-deploy-stage # you can push to this branch to test the stage-deploy process, without having to touch the main branch

jobs:
  deploy-stage:
    name: Deploy stage
    runs-on: ubuntu-latest
    services:
      nightbear_db_test:
        image: postgres:16
        name: nightbear-db-test
        env:
          POSTGRES_USER: nightbear
          POSTGRES_PASSWORD: nightbear_test
          POSTGRES_DB: nightbear
        ports:
          - 35432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    env:
      DATABASE_URL_TEST: postgres://nightbear:nightbear@localhost:35432/nightbear_test
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with: { node-version: '18.16.1' }
      - run: yarn setup:local
      # - run: yarn validate
      - run: docker ps
      - run: docker exec -it nightbear-db-test psql -U nightbear -d nightbear -c 'SELECT true;'
      # - run: yarn test:back
      # - run: 'echo TODO: Deploy to Netlify'
