name: Deploy prod

on:
  release:
    types:
      - created # ...but not e.g. "edited", "deleted" etc

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Print GITHUB_REF for deploy debugging
        run: echo GITHUB_REF=$GITHUB_REF
